export default {
    FETCH_EVENTS_REQUEST: "FETCH_EVENTS_REQUEST",
    FETCH_EVENTS_SUCCESS: "FETCH_EVENTS_SUCCESS",
    FETCH_EVENTS_FAIL: "FETCH_EVENTS_FAIL",
    NOTIFICATION_REGISTER_SUCCESS: "NOTIFICATION_REGISTER_SUCCESS",
    NOTIFICATION_CANCEL_SUCCESS: "NOTIFICATION_CANCEL_SUCCESS",
    NOTIFICATION_CHECK_PERMISSIONS_REQUESTED: "NOTIFICATION_CHECK_PERMISSIONS_REQUESTED" 
}